name: Deploy to S3 (Task-5)
on:
  push:
    branches: [ "main" ]  # run on pushes to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://task5-pavithra-ap-south-1 \
            --delete --exclude ".git/*" --exclude ".github/*" \
            --exclude "AWS_Task_5_Guide.rtf" --exclude "README.md"
